### PR TITLE
feat: allow to integration with lms

### PR DESCRIPTION
**Pull request by Ian2012**
## Description

This PR allows to create an ontask iframe in the instructor panel by changing the X_FRAME_OPTIONS setting and configure the ONTASK_URL variable in the LMS

## Screenshots

image

image

### CODE REVIEW

**Comment by mariajgrimaldi** [comment]
Can you help us figure out why we need to remove the permissions from postgres? This is how MySQL/MongoDB are currently working: https://github.com/overhangio/tutor/blob/74ef1ae56e9bbd4c6a9441a10bb90576136243be/tutor/templates/local/docker-compose.yml#L28-L46

**Comment by Ian2012** [comment]
It's probably related with this file https://github.com/overhangio/tutor/blob/74ef1ae56e9bbd4c6a9441a10bb90576136243be/tutor/templates/apps/permissions/setowners.sh

**Comment by mariajgrimaldi** [comment]
should we do it like that? @Ian2012

**Comment by Ian2012** [comment]
@mariajgrimaldi yes, we should. It's been patched

**Review by mariajgrimaldi — APPROVED** [review]
Thank you!

**Comment by mariajgrimaldi** [comment]
Could you fix the conflicts and then merge? Thanks!

**Pull request merged**
